---

- name: Adding fish directory
  file:
    path: "{{ ansible_user_dir }}/.config/fish"
    state: directory

- name: Adding completions directory
  file:
    path: "{{ ansible_user_dir }}/.config/fish/completions"
    state: directory

- name: Adding functions directory
  file:
    path: "{{ ansible_user_dir }}/.config/fish/functions"
    state: directory

- name: Linking config
  file:
    src: "{{ root_dir}}/fish/config.fish"
    dest: "{{ ansible_user_dir }}/.config/fish/config.fish"
    state: link

- name: Setup fish functions
  file:
    src: "{{ root_dir }}/fish/functions/{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/fish/functions/{{ item }}"
    state: link
  with_items:
    - fish_prompt.fish
    - prompt_pwd.fish
    - vc_prompt.fish
    - get_ip_addr.fish

