---

- hosts: localhost
  roles:
    - common
  tasks:
    - name: Include MacOS role
      include_role:
        name: mac
      when:
        "ansible_facts['distribution'] == 'MacOSX'"

    - name: Include Fedora role
      include_role:
        name: linux
      when:
        "ansible_facts['distribution'] == 'Fedora'"

