# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

export EDITOR=nvim
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -e/etc/profile ]; then
	source /etc/profile
fi

HOST_STR="`ip address show dev tun0 | grep inet | grep -v inet6 | awk -F " " '{print $2}' | awk -F "/" '{print $1}'`"

PS1="\n\[\033[0;33m\]\u\[\033[0;32m\]@\h($HOST_STR)\[\033[0;34m\](\d)(\t)\n\[\033[0;31m\][\w]\[\033[0m\]"

if [ -e $HOME/.git-prompt.sh ]; then
	source $HOME/.git-prompt.sh
	PS1="$PS1\$(__git_ps1)"
fi

if [ -e $HOME/data/hg_extensions/hg-prompt/prompt.py ]; then
	hg_ps1() {
		hg prompt "({branch}:{tags})" 2> /dev/null
	    }

	PS1="$PS1\$(hg_ps1)"
fi

PS1="$PS1\n\[\033[0;32m\]->\[\033[0m\]"
export PS1

export PATH=$PATH:~/bin:~/bin/tmuxifier/bin:/usr/lib/ccache:/opt/bin


if [ -d /home/jjoyce/.tmuxifier_configs ]; then
	eval "$(tmuxifier init -)"
	export TMUXIFIER_LAYOUT_PATH=/home/jjoyce/.tmuxifier_configs
fi

if [ -e /usr/local/bin/virtualenvwrapper.sh ]
then
	export WORKON_HOME=$HOME/virtualenvs
	source /usr/local/bin/virtualenvwrapper.sh
elif [ -e /usr/bin/virtualenvwrapper.sh ]
then

	export WORKON_HOME=$HOME/virtualenvs
	source /usr/bin/virtualenvwrapper.sh
fi

rpm_extract ()
{
	rpm2cpio $1 | cpio -idmv
}

export GOPATH=$HOME/go-stuff
